# -*- coding: utf-8 -*-
"""Data_preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Hxb7jqqqVIU0Z4mBJ1MGPBEE0ingFM1U

#Importing Libraries
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

"""#Load the Dataset"""

df = pd.read_csv("titanicdataset.csv")

"""#understanding Dataset"""

df.head()

df.info()

df.describe()

df.isnull().sum()

"""# Handling missing values"""

df['Age'] = df['Age'].fillna(df['Age'].mean())

df.drop('Cabin', axis=1, inplace=True)

df['Fare'] = df['Fare'].fillna(df['Fare'].mean())

df.duplicated().sum()

df.drop_duplicates(inplace=True)

df.boxplot(column=['Fare'])
plt.show()

Q1 = df['Fare'].quantile(0.25)
Q3 = df['Fare'].quantile(0.75)
IQR = Q3 - Q1
lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR
df = df[(df['Fare'] >= lower) & (df['Fare'] <= upper)]

df['Age'] = (df['Age'] - df['Age'].min()) / (df['Age'].max() - df['Age'].min())

df['Fare'] = (df['Fare'] - df['Fare'].min()) / (df['Fare'].max() - df['Fare'].min())

df['Sex'] = df['Sex'].map({'male':0, 'female':1})

df.isnull().sum()

df.to_csv("Cleaned_Titanic_Dataset.csv", index=False)